// Code generated by "stringer -type TokenType token.go"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[IllegalToken-1]
	_ = x[ClassToken-2]
	_ = x[ConstructorToken-3]
	_ = x[FunctionToken-4]
	_ = x[MethodToken-5]
	_ = x[FieldToken-6]
	_ = x[StaticToken-7]
	_ = x[VarToken-8]
	_ = x[IntToken-9]
	_ = x[CharToken-10]
	_ = x[BooleanToken-11]
	_ = x[VoidToken-12]
	_ = x[TrueToken-13]
	_ = x[FalseToken-14]
	_ = x[NullToken-15]
	_ = x[ThisToken-16]
	_ = x[LetToken-17]
	_ = x[DoToken-18]
	_ = x[IfToken-19]
	_ = x[ElseToken-20]
	_ = x[WhileToken-21]
	_ = x[ReturnToken-22]
	_ = x[LeftBraceToken-23]
	_ = x[RightBraceToken-24]
	_ = x[LeftParenToken-25]
	_ = x[RightParenToken-26]
	_ = x[LeftBraketToken-27]
	_ = x[RightBraketToken-28]
	_ = x[DotToken-29]
	_ = x[CommaToken-30]
	_ = x[SemiColonToken-31]
	_ = x[PlusToken-32]
	_ = x[MinusToken-33]
	_ = x[MultiplyToken-34]
	_ = x[DivideToken-35]
	_ = x[AmpersandToken-36]
	_ = x[PipeToken-37]
	_ = x[GreaterThanToken-38]
	_ = x[LessThanToken-39]
	_ = x[EqualToken-40]
	_ = x[TildeToken-41]
	_ = x[IntegerConstant-42]
	_ = x[StringConstant-43]
	_ = x[IdentifierToken-44]
}

const _TokenType_name = "EOFIllegalTokenClassTokenConstructorTokenFunctionTokenMethodTokenFieldTokenStaticTokenVarTokenIntTokenCharTokenBooleanTokenVoidTokenTrueTokenFalseTokenNullTokenThisTokenLetTokenDoTokenIfTokenElseTokenWhileTokenReturnTokenLeftBraceTokenRightBraceTokenLeftParenTokenRightParenTokenLeftBraketTokenRightBraketTokenDotTokenCommaTokenSemiColonTokenPlusTokenMinusTokenMultiplyTokenDivideTokenAmpersandTokenPipeTokenGreaterThanTokenLessThanTokenEqualTokenTildeTokenIntegerConstantStringConstantIdentifierToken"

var _TokenType_index = [...]uint16{0, 3, 15, 25, 41, 54, 65, 75, 86, 94, 102, 111, 123, 132, 141, 151, 160, 169, 177, 184, 191, 200, 210, 221, 235, 250, 264, 279, 294, 310, 318, 328, 342, 351, 361, 374, 385, 399, 408, 424, 437, 447, 457, 472, 486, 501}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
